# Generated by Django 5.0.6 on 2024-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
